services:
  - type: web
    name: info3-labor
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.web:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
